#!/bin/bash

#command-info: setup dependencies for this application

source bootstrap

npm install -g gulp \
               coffeescript \
               easy-website-generator \
               bower

npm install

bower install

# see https://github.com/sass/node-sass/issues/1804
